### PR TITLE
Flatten messages in PromptBuilder

### PR DESCRIPTION
**Pull request by javipacheco**
This PR closes issue #423 for flattening messages in the `PromBuilder`

When we have a prompt like this

```kotlin
        Prompt {
            +system("Test System")
            +user("User message 1")
            +user("User message 2")
            +assistant("Assistant message 1")
            +user("User message 3")
            +assistant("Assistant message 2")
            +assistant("Assistant message 3")
            +user("User message 4")
          }
```

`Prompt` flattens the intermediate messages with the same role automatically in order to reduce the number of tokens to the AI

### CODE REVIEW

**Comment by raulraja** [comment]
This should be the default behavior and not an operator

**Comment by javipacheco** [comment]
@raulraja I have addressed your proposal in the PR. Could you please review again?

**Review by Intex32 — APPROVED** [review]
Me approves.

**Review by raulraja — APPROVED** [review]
thanks @javipacheco !

**Pull request merged**
